site_name: TFSwitch
site_description: A command line tool to switch between different versions of Terraform (install with Homebrew and more)
copyright: This project is maintained by warrensbox
repo_name: warrensbox/terraform-switcher
repo_url: https://github.com/warrensbox/terraform-switcher
site_url: https://tfswitch.warrensbox.com

theme:
  name: material
  palette:
    primary: indigo
  favicon: static/favicon_tfswitch_16.png
  logo: static/logo.png

nav:
  - Home: index.md
  - Installation: Installation.md
  - Usage:
      - General: usage/general.md
      - Command line: usage/commandline.md
      - Environment variables: usage/environment-variables.md
      - Config files: usage/config-files.md
      - CI/CD: usage/ci-cd.md
  - CI/CD Examples: Continuous-Integration.md
  - Upgrade-or-Uninstall.md
  - How-to-Contribute.md
  - Troubleshoot.md
# WARNING -  Config value 'google_analytics': The configuration option
# google_analytics has been deprecated and will be removed in a future release
# of MkDocs. See the options available on your theme for an alternative.
# See https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/ for new format
#google_analytics:
#  - UA-120055973-1
#  - auto
